# Generated by Django 3.1.4 on 2021-01-01 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('options', models.CharField(max_length=500)),
                ('votes', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
